#!/bin/bash

#gs -q -dNOPAUSE -dBATCH -dPDFSETTINGS=/prepress -sDEVICE=pdfwrite -sOutputFile=output.pdf -dCompatibility=5.0 paper.pdf
#for i in plots*.pdf; do
#	gs -q -dNOPAUSE -dBATCH -dPDFSETTINGS=/prepress -sDEVICE=pdfwrite -sOutputFile=$i.out.pdf $i
#	mv $i.out.pdf $i
#done
#for i in plots*.pdf; do pdftops $i $i.ps && ps2pdf -dPDFSETTINGS=/prepress $i.ps; mv $i.pdf $i; done

pdftops dos.pdf
ps2pdf -dPDFSETTINGS=/prepress dos.ps
